"""
Wind Turbine Reliability Dashboard — Streamlit app.

Run with:
    uv run streamlit run app/app.py

Data is loaded from data/processed/  (parquets generated by notebook 01).
Falls back to synthetic demo data if no processed files are found.
"""

import sys
from pathlib import Path

# Ensure src/ is importable when invoked from any working directory
ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

import numpy as np
import pandas as pd
import streamlit as st

from src.features import (
    compute_anomaly_windows,
    fleet_kpis,
    label_power_curve_status,
)
from src.rca import (
    downtime_pareto,
    failure_pareto,
    monthly_failure_rate,
)
from src.viz import (
    fmt_kpi,
    plot_corrective_timeline,
    plot_failure_heatmap,
    plot_pareto,
    plot_power_curve,
    plot_temp_trend,
)

# ---------------------------------------------------------------------------
# Page config
# ---------------------------------------------------------------------------

st.set_page_config(
    page_title="Wind Turbine Reliability Dashboard",
    page_icon="🌬️",
    layout="wide",
    initial_sidebar_state="expanded",
)

# ---------------------------------------------------------------------------
# Data loading
# ---------------------------------------------------------------------------

PROCESSED = ROOT / "data" / "processed"


def _using_synthetic_data() -> bool:
    """True when no processed SCADA parquet exists (demo mode)."""
    return not (PROCESSED / "scada.parquet").exists()


@st.cache_data(show_spinner="Loading SCADA data…")
def _load_scada() -> pd.DataFrame:
    p = PROCESSED / "scada.parquet"
    if p.exists():
        return pd.read_parquet(p)
    return _synthetic_scada()


@st.cache_data(show_spinner="Loading logbook…")
def _load_logbook() -> pd.DataFrame:
    p = PROCESSED / "logbook.parquet"
    if p.exists():
        return pd.read_parquet(p)
    return _synthetic_logbook()


def _synthetic_scada(n: int = 26_280) -> pd.DataFrame:
    """Two years of 10-min data for 4 synthetic turbines."""
    rng = np.random.default_rng(42)
    timestamps = pd.date_range("2022-01-01", periods=n, freq="10min")
    turbines = ["T01", "T02", "T03", "T04"]
    frames = []
    for tid in turbines:
        ws = np.clip(rng.weibull(2, n) * 8 + rng.normal(0, 0.5, n), 0, 30)
        ambient = 10 + 8 * np.sin(2 * np.pi * np.arange(n) / (365 * 144)) + rng.normal(0, 2, n)
        gear_temp = ambient + 38 + rng.normal(0, 2, n)
        pwr = np.clip(200 * np.maximum(ws - 3.5, 0) ** 2.5, 0, 2000) * rng.uniform(0.9, 1.02, n)
        frames.append(pd.DataFrame({
            "turbine_id": tid,
            "timestamp": timestamps,
            "wind_speed_ms": ws.round(2),
            "active_power_kw": pwr.round(1),
            "gearbox_oil_temp_c": gear_temp.round(2),
            "gearbox_bearing_temp_c": (gear_temp + rng.normal(2, 1, n)).round(2),
            "generator_winding_temp_c": (ambient + 55 + rng.normal(0, 3, n)).round(2),
            "ambient_temp_c": ambient.round(2),
        }))
    # NB: do not emit Streamlit elements (st.toast/st.warning/…) here — this
    # function is wrapped in @st.cache_data and the element would be replayed
    # from cache on every rerun, raising CacheReplayClosureError on interaction.
    return pd.concat(frames, ignore_index=True)


def _synthetic_logbook() -> pd.DataFrame:
    events = [
        ("2022-02-14", "T01", "Gearbox",         "Oil leak — main seal",        48.0),
        ("2022-04-03", "T02", "Generator",        "Winding insulation fault",    36.0),
        ("2022-05-20", "T03", "Gearbox",          "High-speed shaft bearing",    72.0),
        ("2022-07-11", "T01", "Hydraulic Group",  "Pitch hydraulic seal failure", 12.0),
        ("2022-08-29", "T04", "Transformer",      "Overheating / cooling fault", 24.0),
        ("2022-10-05", "T02", "Gearbox",          "Planet gear pitting",         96.0),
        ("2022-11-18", "T03", "Generator",        "Bearing replacement",         48.0),
        ("2023-01-07", "T01", "Gearbox",          "Gearbox oil filter blocked",  16.0),
        ("2023-03-22", "T04", "Rotor",            "Blade leading-edge erosion",  120.0),
        ("2023-05-14", "T02", "Hydraulic Group",  "Hydraulic pump replacement",  20.0),
        ("2023-06-30", "T01", "Transformer",      "Oil leak — transformer",      18.0),
        ("2023-08-15", "T03", "Gearbox",          "Gear tooth wear — stage 2",   60.0),
    ]
    df = pd.DataFrame(events, columns=["timestamp", "turbine_id", "component", "failure_mode", "duration_hours"])
    df["timestamp"] = pd.to_datetime(df["timestamp"])
    df["work_order_type"] = "Corrective"
    return df


# ---------------------------------------------------------------------------
# Main app
# ---------------------------------------------------------------------------

def main() -> None:
    st.title("🌬️ Wind Turbine Reliability Dashboard")
    st.caption("EDP Open Data · SCADA + Failure Logbook · Portfolio Project")

    scada_raw = _load_scada()
    logbook   = _load_logbook()

    if _using_synthetic_data():
        st.info(
            "Showing **synthetic demo data** (2 years · 4 turbines). "
            "Add EDP parquets to `data/processed/` to use real data.",
            icon="ℹ️",
        )

    # ---- Sidebar -------------------------------------------------------
    st.sidebar.header("Filters")

    turbines_all = sorted(scada_raw["turbine_id"].unique()) if "turbine_id" in scada_raw.columns else []
    selected_turbines = st.sidebar.multiselect(
        "Turbines", turbines_all, default=turbines_all,
    )

    date_min = scada_raw["timestamp"].min().date() if "timestamp" in scada_raw.columns else None
    date_max = scada_raw["timestamp"].max().date() if "timestamp" in scada_raw.columns else None
    if date_min and date_max:
        date_range = st.sidebar.date_input(
            "Date range",
            value=(date_min, date_max),
            min_value=date_min,
            max_value=date_max,
        )
    else:
        date_range = None

    temp_col_options = [c for c in scada_raw.columns if "temp" in c and "ambient" not in c]
    temp_col = st.sidebar.selectbox(
        "Temperature signal (trend panel)",
        temp_col_options,
        index=0 if temp_col_options else None,
    )

    rated_power = st.sidebar.number_input("Rated power (kW)", value=2000, step=100)

    st.sidebar.divider()
    st.sidebar.markdown("**Data source**")
    st.sidebar.markdown(
        "Place EDP SCADA CSVs in `data/raw/scada/` and run "
        "`notebooks/01_data_loading.ipynb` to replace demo data."
    )

    # ---- Apply filters -------------------------------------------------
    scada = scada_raw.copy()
    if selected_turbines and "turbine_id" in scada.columns:
        scada = scada[scada["turbine_id"].isin(selected_turbines)]
    if date_range and len(date_range) == 2 and "timestamp" in scada.columns:
        scada = scada[
            (scada["timestamp"].dt.date >= date_range[0]) &
            (scada["timestamp"].dt.date <= date_range[1])
        ]

    log_filtered = logbook.copy()
    if selected_turbines and "turbine_id" in logbook.columns:
        log_filtered = logbook[logbook["turbine_id"].isin(selected_turbines)]
    if date_range and len(date_range) == 2 and "timestamp" in logbook.columns:
        log_filtered = log_filtered[
            (log_filtered["timestamp"].dt.date >= date_range[0]) &
            (log_filtered["timestamp"].dt.date <= date_range[1])
        ]

    # Turbines actually in view after the sidebar filter — drives the per-panel
    # selectboxes so you can't pick a turbine that's been filtered out.
    turbines_view = selected_turbines if selected_turbines else turbines_all

    if not turbines_view:
        st.warning("No turbines selected — pick at least one in the sidebar.")
        return

    # ---- KPI strip -----------------------------------------------------
    st.subheader("Fleet KPIs")
    kpis = fleet_kpis(scada, log_filtered)
    kpi_fmt = fmt_kpi(kpis)

    k1, k2, k3, k4 = st.columns(4)
    k1.metric(
        "Fleet Availability", kpi_fmt["Fleet Availability"],
        help="(Scheduled hours − Downtime hours) / Scheduled hours, averaged across selected turbines.",
    )
    k2.metric(
        "Fleet MTBF", kpi_fmt["Fleet MTBF"],
        help="Mean operating time between failures, averaged across turbines.",
    )
    k3.metric(
        "Failure Events", kpi_fmt["Failure Events"],
        help="Total logged corrective repair/replacement events in the current filter.",
    )
    k4.metric(
        "Total Downtime", kpi_fmt["Total Downtime"],
        help="Sum of all logged event durations (hours) in the current filter.",
    )

    st.divider()

    # ---- Row 1: Power curve + Pareto -----------------------------------
    col1, col2 = st.columns(2)

    with col1:
        st.subheader("Power Curve")
        turbine_filter = st.selectbox(
            "Filter to turbine (or All)",
            ["All"] + turbines_view,
            key="pc_turbine",
        )
        scada_labeled = label_power_curve_status(scada, rated_power_kw=rated_power)
        fig_pc = plot_power_curve(
            scada_labeled,
            turbine_id=None if turbine_filter == "All" else turbine_filter,
            rated_power_kw=rated_power,
        )
        st.plotly_chart(fig_pc, width="stretch")

    with col2:
        st.subheader("Failure Pareto")
        pareto_mode = st.radio("Measure", ["Count", "Downtime (h)"], horizontal=True, key="pareto_mode")
        if pareto_mode == "Count":
            pareto_df = failure_pareto(log_filtered)
            fig_pareto = plot_pareto(pareto_df, value_label="Failure Count")
        else:
            if "duration_hours" in log_filtered.columns:
                pareto_df = downtime_pareto(log_filtered)
                fig_pareto = plot_pareto(pareto_df, value_label="Downtime (h)",
                                         title="Downtime Pareto by Component")
            else:
                pareto_df = failure_pareto(log_filtered)
                fig_pareto = plot_pareto(pareto_df, value_label="Failure Count")
                st.warning("duration_hours not available — showing count instead.")
        st.plotly_chart(fig_pareto, width="stretch")

    st.divider()

    # ---- Row 2: Temperature trend + Corrective timeline ----------------
    col3, col4 = st.columns(2)

    with col3:
        st.subheader("Temperature Trend & Anomaly Windows")
        if temp_col:
            trend_turbine = st.selectbox(
                "Turbine", turbines_view, key="trend_turbine",
            ) if turbines_view else None

            gear_log = log_filtered[
                log_filtered["component"].str.contains("Gearbox", na=False)
            ] if "component" in log_filtered.columns else log_filtered

            # Anomaly windows are per-turbine, and only one turbine is shown —
            # compute on just that turbine to keep interactions snappy.
            scada_trend = (
                scada[scada["turbine_id"] == trend_turbine]
                if trend_turbine and "turbine_id" in scada.columns
                else scada
            )

            try:
                scada_anom = compute_anomaly_windows(
                    scada_trend, gear_log,
                    temp_col=temp_col,
                    window_days=7,
                    ambient_col="ambient_temp_c" if "ambient_temp_c" in scada.columns else None,
                )
                fig_temp = plot_temp_trend(
                    scada_anom,
                    turbine_id=trend_turbine,
                    logbook=gear_log,
                    title=f"Temperature Trend — {trend_turbine or 'Fleet'}",
                )
                st.plotly_chart(fig_temp, width="stretch")
            except Exception as e:
                st.error(f"Temperature trend error: {e}")
        else:
            st.info("No temperature columns found in SCADA data.")

    with col4:
        st.subheader("Corrective Actions Timeline")
        try:
            fig_tl = plot_corrective_timeline(log_filtered)
            st.plotly_chart(fig_tl, width="stretch")
        except Exception as e:
            st.error(f"Timeline error: {e}")

    st.divider()

    # ---- Monthly failure heatmap ---------------------------------------
    st.subheader("Monthly Failure Rate by Component")
    try:
        monthly = monthly_failure_rate(log_filtered)
        if not monthly.empty and "component" in monthly.columns:
            fig_heat = plot_failure_heatmap(monthly)
            st.plotly_chart(fig_heat, width="stretch")
        else:
            st.info("Not enough logbook data for heatmap.")
    except Exception as e:
        st.error(f"Heatmap error: {e}")

    st.divider()

    # ---- Raw data expanders -------------------------------------------
    with st.expander("SCADA data (filtered)"):
        st.dataframe(scada.head(500), width="stretch")

    with st.expander("Logbook (filtered)"):
        st.dataframe(log_filtered, width="stretch")


if __name__ == "__main__":
    main()
